# WARNING!
# This is a development version of the docker-compose.yml file.
# Avoid using this file in your production environment.
# We're exposing here sensitive ports and mounting code volumes for rapid development and debugging of the server stack.

x-logging: &x-logging
  logging:
    driver: 'json-file'
    options:
      max-file: '5'
      max-size: '10m'

version: '3'

services:
  openruntimes-proxy:
    container_name: openruntimes-proxy
    <<: *x-logging
    build:
      context: .
    networks:
      servers:
    ports:
      - 9800:80
    volumes:
      - ./app:/usr/local/app:rw
      - ./src:/usr/local/src:rw
      - ./tests:/usr/local/tests:rw
    environment:
      - OPR_PROXY_ALGORITHM
      - OPR_PROXY_WORKER_PER_CORE
      - OPR_PROXY_EXECUTORS
      - OPR_PROXY_HEALTHCHECK_INTERVAL
      - OPR_PROXY_MAX_TIMEOUT
      - OPR_PROXY_ENV
      - OPR_PROXY_EXECUTOR_SECRET
      - OPR_PROXY_SECRET
      - OPR_PROXY_LOGGING_PROVIDER
      - OPR_PROXY_LOGGING_CONFIG
      - OPR_PROXY_HEALTHCHECK
      - OPR_PROXY_HEALTHCHECK_URL
      - OPR_PROXY_CONNECTIONS_STATE
    depends_on:
      redis-cluster-0:
        condition: service_healthy

  redis:
    image: redis:6.0-alpine
    container_name: redis
    networks:
      servers:
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping" ]
      start_interval: 1s

  redis-cluster-0:
    image: docker.io/bitnami/redis-cluster:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-cluster-0 redis-cluster-1 redis-cluster-2 redis-cluster-3
      - REDIS_CLUSTER_CREATOR=yes
      - REDIS_CLUSTER_REPLICAS=0
    networks:
      servers:
    depends_on:
      redis-cluster-1:
        condition: service_started
      redis-cluster-2:
        condition: service_started
      redis-cluster-3:
        condition: service_started
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping" ]
      start_interval: 1s

  redis-cluster-1:
    image: docker.io/bitnami/redis-cluster:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-cluster-0 redis-cluster-1 redis-cluster-2 redis-cluster-3
    networks:
      servers:
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping" ]
      start_interval: 1s

  redis-cluster-2:
    image: docker.io/bitnami/redis-cluster:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-cluster-0 redis-cluster-1 redis-cluster-2 redis-cluster-3
    networks:
      servers:
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping" ]
      start_interval: 1s

  redis-cluster-3:
    image: docker.io/bitnami/redis-cluster:7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-cluster-0 redis-cluster-1 redis-cluster-2 redis-cluster-3
    networks:
      servers:
    healthcheck:
      test: [ "CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping" ]
      start_interval: 1s

  mockoon1:
    container_name: mockoon1
    image: mockoon/cli:2.2.1
    command: mockoon-cli start --data /data
    networks:
      servers:
    volumes:
      - ./mockoon.json:/data:ro

  mockoon2:
    container_name: mockoon2
    image: mockoon/cli:2.2.1
    command: mockoon-cli start --data /data
    networks:
      servers:
    volumes:
      - ./mockoon.json:/data:ro

  mockoon3:
    container_name: mockoon3
    image: mockoon/cli:2.2.1
    command: mockoon-cli start --data /data
    networks:
      servers:
    volumes:
      - ./mockoon.json:/data:ro

  mockoon4:
    container_name: mockoon4
    image: mockoon/cli:2.2.1
    command: mockoon-cli start --data /data
    networks:
      servers:
    volumes:
      - ./mockoon.json:/data:ro

  mockoon5:
    container_name: mockoon5
    image: mockoon/cli:2.2.1
    command: mockoon-cli start --data /data
    networks:
      servers:
    volumes:
      - ./mockoon.json:/data:ro

networks:
  servers:

