name: "Release"

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - run: git checkout HEAD^2

    - name: Build Docker Image
      run:  |
        export COMPOSE_INTERACTIVE_NO_CLI
        export DOCKER_BUILDKIT=1
        export COMPOSE_DOCKER_CLI_BUILD=1
        export BUILDKIT_PROGRESS=plain
        docker build -t openruntimes/proxy:latest .

    - name: Push Docker Image
      run: docker push openruntimes/proxy:latest